### ISSUE TITLE
[Epic] Project kickoff

### ISSUE THREAD

**Issue by calvinkmts** [Hack-Weekly/cerulean-lion-chat-app#1]
**Background**

We are building a real-time chat app, and we have decided on using flask and react. 

Now we need to start it, so everybody can be on the same page. let's start with setting up the project. what kind of structure we are going to use and etc. 

React-flask-app project layout example: https://github.com/miguelgrinberg/react-flask-app 

flask project example: https://flask.palletsprojects.com/en/2.2.x/tutorial/layout/

react project example: https://github.com/WebDevSimplified/react-folder-structure or 
https://github.com/alan2207/bulletproof-react/blob/master/docs/project-structure.md

**Todo**

- [ ] [[Task](https://github.com/Hack-Weekly/cerulean-lion-chat-app/issues/3)]Setting up a new flask project in api directory 
- [ ] [[Task](https://github.com/Hack-Weekly/cerulean-lion-chat-app/issues/2)] Setting up a new react project in root directory
- [ ] Decide on which database we are going to use and write a docker deployment so everybody can run the project locally with ease
