### ISSUE TITLE
[Project Structure] Setup react project 

### ISSUE THREAD

**Issue by calvinkmts** [Hack-Weekly/cerulean-lion-chat-app#2]
**Background**

We have decided on using react, let's make a structure that everyone can follow easily and start development much easier. 

Reference: 

- https://github.com/WebDevSimplified/react-folder-structure
- https://github.com/alan2207/bulletproof-react/blob/master/docs/project-structure.md

**Todo**

- [ ] Setup new react project 
- [ ] Update README.md on the requirements for running the react app
- [ ] Update README.md on how to run the react app

**Definition of Done**

- [ ] I can follow along what the README.md said and I can run the project locally

**Comment by tjnaz** [comment]
Hi, I'm new here. Are we using both react and flask for this project? because I noticed that issue#3 is about setting up a flask project.
Thanks.

**Comment by calvinkmts** [comment]
yes @AnazThaj we decided to use both flask and react for this project. because some of the team member is experienced in flask hoping that it can speed up the development and setup on the project to.

**Comment by tjnaz** [comment]
> yes @AnazThaj we decided to use both flask and react for this project. because some of the team member is experienced in flask hoping that it can speed up the development and setup on the project to. 

That's great. Thanks for the reply.
