### ISSUE TITLE
[Project Structure] Setup flask project

### ISSUE THREAD

**Issue by calvinkmts** [Hack-Weekly/cerulean-lion-chat-app#3]
**Background**

We have decided on using flask, let's make a structure that everyone can follow easily and start development much easier.

Reference:

- https://github.com/miguelgrinberg/react-flask-app

**Todo**

- [ ]  Setup new flask project
- [ ]  Update README.md on the requirements for running the react app
- [ ]  Update README.md on how to run the react app

**Definition of Done**

- [ ] I can follow along what the README.md said and I can run the project locally
